# Generated by Django 5.2.10 on 2026-02-08 00:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmuConfigurationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la configuración (ej: CSR-4, Toshiba-3)', max_length=50, unique=True, verbose_name='Nombre')),
                ('manufacturer', models.CharField(help_text='CSR Zhuzhou o Toshiba', max_length=100, verbose_name='Fabricante')),
                ('coach_sequence', models.JSONField(help_text="Lista ordenada de tipos de coche (ej: ['mc1', 'r1', 'r2', 'mc2'])", verbose_name='Secuencia de coches')),
                ('min_coaches', models.PositiveSmallIntegerField(verbose_name='Mínimo de coches')),
                ('max_coaches', models.PositiveSmallIntegerField(verbose_name='Máximo de coches')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración de EMU',
                'verbose_name_plural': 'Configuraciones de EMU',
                'db_table': 'fleet_emu_configuration',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmuModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='Identificador del módulo (ej: M01, T15)', max_length=20, unique=True, verbose_name='Número de módulo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('manufacturer', models.CharField(help_text='CSR Zhuzhou o Toshiba', max_length=100, verbose_name='Fabricante')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fabricación')),
                ('commissioning_date', models.DateField(verbose_name='Fecha de puesta en servicio')),
                ('line', models.CharField(blank=True, help_text='Línea ferroviaria (ej: LR = Línea Roca)', max_length=10, null=True, verbose_name='Línea')),
                ('voltage', models.PositiveIntegerField(default=25000, help_text='Voltaje de operación en voltios', verbose_name='Voltaje (V)')),
                ('max_speed', models.PositiveSmallIntegerField(default=120, verbose_name='Velocidad máxima (km/h)')),
                ('total_passenger_capacity', models.PositiveIntegerField(default=0, verbose_name='Capacidad total de pasajeros')),
                ('legacy_id', models.PositiveIntegerField(blank=True, help_text='Id_Módulos de la base Access', null=True, unique=True, verbose_name='ID legacy (Access)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emus', to='database.emuconfigurationmodel', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'EMU (Módulo)',
                'verbose_name_plural': 'EMUs (Módulos)',
                'db_table': 'fleet_emu',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='CoachModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='Número identificador del coche (ej: 5001, 4029)', max_length=20, unique=True, verbose_name='Número de coche')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fabricación')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Fecha de puesta en servicio')),
                ('line', models.CharField(blank=True, max_length=10, null=True, verbose_name='Línea')),
                ('coach_type', models.CharField(choices=[('mc1', 'MC1 - Motriz Cabecera 1'), ('mc2', 'MC2 - Motriz Cabecera 2'), ('r1', 'R1 - Remolque'), ('r2', 'R2 - Remolque Prima'), ('m', 'M - Motriz'), ('r', 'R - Remolque'), ('rp', 'RP - Remolque Prima')], max_length=10, verbose_name='Tipo de coche')),
                ('voltage', models.PositiveIntegerField(blank=True, help_text='Solo para coches motrices', null=True, verbose_name='Voltaje (V)')),
                ('has_pantograph', models.BooleanField(default=False, verbose_name='Tiene pantógrafo')),
                ('has_cabin', models.BooleanField(default=False, verbose_name='Tiene cabina')),
                ('place', models.PositiveSmallIntegerField(blank=True, help_text='Posición del coche dentro del módulo (1..N)', null=True, verbose_name='Posición en EMU')),
                ('seating_capacity', models.PositiveSmallIntegerField(default=0, verbose_name='Capacidad de asientos')),
                ('legacy_id', models.PositiveIntegerField(blank=True, help_text='Id_Coches de la base Access', null=True, verbose_name='ID legacy (Access)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('emu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='database.emumodel', verbose_name='EMU (Módulo)')),
            ],
            options={
                'verbose_name': 'Coche',
                'verbose_name_plural': 'Coches',
                'db_table': 'fleet_coach',
                'ordering': ['emu', 'place'],
            },
        ),
        migrations.CreateModel(
            name='FormationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(help_text='Identificador de la formación (ej: F120)', max_length=20, unique=True, verbose_name='ID de formación')),
                ('unit_number', models.CharField(max_length=20, verbose_name='Número de formación')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Fecha de puesta en servicio')),
                ('line', models.CharField(blank=True, max_length=10, null=True, verbose_name='Línea')),
                ('route', models.CharField(blank=True, help_text='Ej: Constitución - La Plata', max_length=100, null=True, verbose_name='Recorrido')),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID legacy (Access)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('emus', models.ManyToManyField(blank=True, related_name='formations', to='database.emumodel', verbose_name='EMUs')),
            ],
            options={
                'verbose_name': 'Formación',
                'verbose_name_plural': 'Formaciones',
                'db_table': 'fleet_formation',
                'ordering': ['f_id'],
            },
        ),
    ]
