# Generated by Django 5.2.10 on 2026-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgCoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coche', models.IntegerField(unique=True, verbose_name='Número de coche')),
                ('posicion', models.IntegerField(blank=True, null=True, verbose_name='Posición')),
                ('ubicacion', models.CharField(blank=True, default='', help_text='Tipo lógico: MC1, MC2, R1, R2, MC, R, RP', max_length=50, verbose_name='Ubicación')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Staging: Coche',
                'verbose_name_plural': 'Staging: Coches',
                'db_table': 'stg_coche',
                'ordering': ['coche'],
            },
        ),
        migrations.CreateModel(
            name='StgModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.IntegerField(unique=True, verbose_name='Id_Módulos (Access)')),
                ('nombre', models.CharField(help_text='Ej: M01, T06', max_length=20, verbose_name='Módulos')),
                ('clase_vehiculo', models.IntegerField(blank=True, null=True, verbose_name='Clase_Vehículos (FK Access)')),
                ('tipo_mr', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo_MR')),
                ('marca_mr', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca_MR')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Staging: Módulo',
                'verbose_name_plural': 'Staging: Módulos',
                'db_table': 'stg_modulo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='StgFormacionModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_access_id', models.IntegerField(db_index=True, verbose_name='Módulo (FK Access)')),
                ('coche', models.IntegerField(verbose_name='Número de coche')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Staging: Formación-Módulo',
                'verbose_name_plural': 'Staging: Formaciones-Módulos',
                'db_table': 'stg_formacion_modulo',
                'constraints': [models.UniqueConstraint(fields=('modulo_access_id', 'coche'), name='uq_stg_form_modulo_coche')],
            },
        ),
        migrations.CreateModel(
            name='StgKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_access_id', models.IntegerField(db_index=True, verbose_name='Módulo (FK Access)')),
                ('fecha', models.DateField(verbose_name='Fecha de lectura')),
                ('kilometraje', models.BigIntegerField(blank=True, null=True, verbose_name='Kilometraje acumulado')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Staging: Kilometraje',
                'verbose_name_plural': 'Staging: Kilometrajes',
                'db_table': 'stg_kilometraje',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='ix_stg_km_fecha'), models.Index(fields=['modulo_access_id', '-fecha'], name='ix_stg_km_modulo_fecha_desc')],
                'constraints': [models.UniqueConstraint(fields=('modulo_access_id', 'fecha'), name='uq_stg_km_modulo_fecha')],
            },
        ),
        migrations.CreateModel(
            name='StgOtSimaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_access_id', models.IntegerField(db_index=True, verbose_name='Módulo (FK Access)')),
                ('tipo_tarea', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo_Tarea')),
                ('tarea', models.CharField(blank=True, default='', help_text='Código de tarea: IQ, AN1, BA2, RB, RG, MEN, etc.', max_length=50, verbose_name='Tarea')),
                ('km', models.BigIntegerField(blank=True, null=True, verbose_name='Km al momento de la OT')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio de la OT')),
                ('fecha_fin', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha fin de la OT')),
                ('ot_simaf', models.CharField(blank=True, default='', help_text='Número de OT en sistema SIMAF', max_length=100, verbose_name='OT SIMAF')),
                ('access_row_hash', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Hash de fila (dedup)')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Staging: OT SIMAF',
                'verbose_name_plural': 'Staging: OTs SIMAF',
                'db_table': 'stg_ot_simaf',
                'ordering': ['-fecha_fin'],
                'indexes': [models.Index(fields=['modulo_access_id', '-fecha_fin'], name='ix_stg_ot_modulo_fecha_desc'), models.Index(fields=['tarea', '-fecha_fin'], name='ix_stg_ot_tarea_fecha_desc')],
            },
        ),
    ]
