# Generated by Django 5.2.10 on 2026-02-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_staging_raw_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('success', 'Completado'), ('failed', 'Fallido')], default='running', max_length=20, verbose_name='Estado')),
                ('tables_synced', models.JSONField(blank=True, default=dict, help_text='{"modulos": 114, "kilometrajes": 191182, ...}', verbose_name='Tablas sincronizadas')),
                ('log_output', models.TextField(blank=True, default='', verbose_name='Salida del log')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Log de sincronización',
                'verbose_name_plural': 'Logs de sincronización',
                'db_table': 'sync_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
